using System;
using System.Text;

using KNSoft.C4Lib;

namespace KNSoft.Precomp4C;

public static class CodeFragment
{
    public static readonly Byte[] Utf8Bom = { 0xEF, 0xBB, 0xBF };

    public static readonly Byte[] AutoGenerateComment = Encoding.UTF8.GetBytes(
        "//------------------------------------------------------------------------------\r\n" +
        "// <auto-generated>\r\n" +
        "//     This code was generated by " + MetaInfo.ProductName + "\r\n" +
        "//     " + MetaInfo.CompanyName + " - " + MetaInfo.ProductName + "\r\n" +
        "//     " + MetaInfo.FindMetadata("RepositoryUrl") + "\r\n" +
        "//     Do not change this file manually\r\n" +
        "// </auto-generated>\r\n" +
        "//------------------------------------------------------------------------------\r\n\r\n");

    public static readonly Byte[] PragmaOnce = "#pragma once\r\n\r\n"u8.ToArray();
}
