name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    permissions:
      contents: read
    strategy:
      matrix:
        configuration: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
          submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build
      run: msbuild .\Source\KNSoft.Precomp4C.sln /restore /m /p:Configuration=${{matrix.configuration}} /p:Platform="Any CPU"
  Publish:
    if: ${{github.base_ref == '' && startsWith(github.event.head_commit.message, '[VERSION] ')}}
    needs: Build
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - name: Set release version
      id: relver
      shell: pwsh
      run: |
        $relver="${{github.event.head_commit.message}}".Substring(10)
        Write-Output "relver=$relver">>$env:GITHUB_OUTPUT
    - name: Source checkout
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build and create NuGet package
      run: msbuild .\Source\KNSoft.Precomp4C.sln /restore /t:pack /p:Configuration=Release /p:Platform="Any CPU"
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: v${{steps.relver.outputs.relver}}
        tag_name: v${{steps.relver.outputs.relver}}
        body: "**NuGet Package**: https://www.nuget.org/packages/KNSoft.Precomp4C/${{steps.relver.outputs.relver}}"
        prerelease: true
        preserve_order: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: ./Source/bin/Release/KNSoft.Precomp4C.${{steps.relver.outputs.relver}}.nupkg
