name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .\Source\KNSoft.Precomp4C.sln

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
          submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /restore /m /p:Configuration=${{matrix.configuration}} /p:Platform="Any CPU" ${{env.SOLUTION_FILE_PATH}}
